version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    ports:
      - "8000:8000"
    volumes:
      - memory-data:/app/memory

volumes:
  memory-data:
