name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install frontend deps
        run: |
          cd packages/frontend
          pnpm install

      - name: Build frontend
        run: |
          cd packages/frontend
          pnpm build

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend deps
        run: |
          cd packages/backend
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run tests
        run: |
          PYTHONPATH=packages/backend pytest -q
